### ISSUE TITLE
Visionaire cannot run RTSP password with special chars

### ISSUE THREAD

**Issue by ekkirinaldi** [nodefluxio/docker-stream-quickstart#3]
I'm running a camera with an RTSP password that looks like this `support@!@#456`, but Visionaire returns a black blank screen in Vanilla. Here's my full rtsp link `rtsp://admin:support@!@#456@192.168.100.1:554/Streaming/Channels/1`

When I turn the password into URL encode still doesn't work `support%40!%40#456` 

Here's the result
![image](https://user-images.githubusercontent.com/22832454/142898812-0ac886d5-c660-45cf-9a4c-c7a7b761219f.png)

Here's the Visionaire logs (looks fine I think)
![image](https://user-images.githubusercontent.com/22832454/142899358-2dc0325a-63ca-4786-a7ee-3eee4c2c09cf.png)

**Comment by ekkirinaldi** [comment]
Update from Developer:

_We will observe the case, will update soon_

**Comment by ekkirinaldi** [comment]
We suggest changing the password without using special char for now

**Comment by jaxz04-nf** [comment]
hi ekki,

i suggest this task to be not closed while this issues not solve yet on our side. 

thanks.
